version: 2

env:
  - GO111MODULE=on
  # ARM crypto extension for RANDOM Number generation
  - GOARM64=v8.0,crypto
  - CFLAGS="-O3"
  - CXXFLAGS="-O3"

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags: -s -w
    goarch:
      - amd64
      - arm64
    main: ./cmd/gemini
    goamd64:
      - v3 # v3 Enables AMD64 SIMD (SSE4.x,AVX2) optimizations

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE

source:
  enabled: true
  format: 'tar.gz'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - scylladb/gemini:{{ .Version }}-amd64
    goarch: amd64
    goamd64: v3
    goos: linux
    id: gemini-amd64
    build_flag_templates:
      - '--platform=linux/amd64'
      - '--target=production-goreleaser'

  - image_templates:
      - scylladb/gemini:{{ .Version }}-arm64v8
    goarch: arm64
    id: gemini-arm
    goos: linux
    build_flag_templates:
      - '--platform=linux/arm64/v8'
      - '--target=production-goreleaser'

docker_manifests:
  - name_template: 'scylladb/gemini:{{ .Version }}'
    skip_push: false
    image_templates:
      - 'scylladb/gemini:{{ .Version }}-amd64'
      - 'scylladb/gemini:{{ .Version }}-arm64v8'

  - name_template: 'scylladb/gemini:latest'
    skip_push: false
    image_templates:
      - 'scylladb/gemini:{{ .Version }}-amd64'
      - 'scylladb/gemini:{{ .Version }}-arm64v8'

release:
  mode: keep-existing
  make_latest: true
  prerelease: auto
  skip_upload: false
