networks:
  gemini:
    name: gemini
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24

services:
  gemini-oracle:
    image: cassandra:3.11.3
    container_name: gemini-oracle
    networks:
      gemini:

  gemini-test:
    image: scylladb/scylla:${SCYLLA_TEST_VERSION:-6.1.1}
    container_name: gemini-test
    command: --smp 1 --memory 512M --api-address 0.0.0.0
    networks:
      gemini:
