env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
s3:
  -
    bucket: downloads.scylladb.com
    region: us-east-1
    folder: "gemini/{{.Version}}"
    acl: public-read
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
