version: '3.5'

networks:
  gemini:
    name: gemini
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24

services:
  gemini-oracle:
    image: scylladb/scylla:5.2.2
    container_name: gemini-oracle
    command: --smp 2 --memory 512M --api-address 0.0.0.0
    networks:
      gemini:

  gemini-test:
    image: scylladb/scylla:5.2.2
    container_name: gemini-test
    command: --smp 2 --memory 512M --api-address 0.0.0.0
    networks:
      gemini:
