name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    env:
    runs-on: ubuntu-latest
    steps:
      - steps:
          - uses: actions/checkout@v2
          - name: Setup Go
            uses: actions/setup-go@v2
            with:
              go-version: latest

          - name: Unit Tests
              run: go test -v -race ./...

          - name: Build
              run: go build .