name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Lint Test and Build
    runs-on: ubuntu-24.04
    steps:
      - name:
        uses: actions/checkout@v4
      - name: Pull tags and refs
        run: git fetch --prune --unshallow
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Linting
        run: make check
      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          repo: gotestfmt
          version: v2.2.0
      - name: Unit Tests
        run: make test
      - name: Build
        run: make build
