name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint Test and Build
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: actions/checkout@v3
      - name: Pull tags and refs
        run: git fetch --prune --unshallow
      - name: Check if version is updated
        run: |
          export ExpectedVersion=$(git describe --tags --abbrev=0)
          export DefinedVersion=$(cat cmd/gemini/Version)
          if [ "$ExpectedVersion" != "$DefinedVersion" ]; then 
            echo "Expect to have '$ExpectedVersion', but got '$DefinedVersion'"
            exit 1
          fi
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4

      - name: Linting
        run: |
          make check

      - name: Unit Tests
        run: |
          go test -v -race ./...

      - name: Build
        run: |
          go build ./cmd/gemini/
