name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint Test and Build
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4

      - name: Linting
        run: |
          make check

      - name: Unit Tests
        run: |
          go test -v -race ./...

      - name: Build
        run: |
          go build ./cmd/gemini/
